//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorMovies.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorMovies.Shared.Resources.IndexResources", typeof(IndexResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flix Manager is a progressive web application to manage a library of movies that illustrates, from the ground up, all the major topics that any
        ///    aspiring full stack .Net.
        /// </summary>
        public static string Index1_1 {
            get {
                return ResourceManager.GetString("Index1.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to developer should be familiar with. It lays out a background, explains,
        ///    provides data sources, and demonstrates the practical implementation of each
        ///    subject..
        /// </summary>
        public static string Index1_2 {
            get {
                return ResourceManager.GetString("Index1.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flix Manager was born in my journey to transition from a desktop applications
        ///    to a web applications developer and I sincerely hope it is of some use to
        ///    other fellow developers that wish to make the same progression. Its instructional
        ///    section is a collection of data from multiple sources curated with a zero experience
        ///    developer in mind to aid in his/her passage to become a full stack .Net Blazor developer..
        /// </summary>
        public static string Index2_1 {
            get {
                return ResourceManager.GetString("Index2.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I chose an application to manage a library of movies because there are plenty of similar projects and data from.
        /// </summary>
        public static string Index3_1 {
            get {
                return ResourceManager.GetString("Index3.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the creator of.
        /// </summary>
        public static string Index3_2 {
            get {
                return ResourceManager.GetString("Index3.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string Index3_3 {
            get {
                return ResourceManager.GetString("Index3.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This makes it fairly trouble-free to research diverse approaches to achieve the ultimate goal of producing a progressive web application that adheres to the current industry standards..
        /// </summary>
        public static string Index3_4 {
            get {
                return ResourceManager.GetString("Index3.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Although the outline of the subjects in the development of the Flix Manager application is based on the.
        /// </summary>
        public static string Index4_1 {
            get {
                return ResourceManager.GetString("Index4.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to course by Felipe Gavilán, its implementation is heavily modified. Specially as it moves forward towards the more advanced topics. Nevertheless, I.
        /// </summary>
        public static string Index4_2 {
            get {
                return ResourceManager.GetString("Index4.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strongly.
        /// </summary>
        public static string Index4_3 {
            get {
                return ResourceManager.GetString("Index4.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recommend checking out his course at.
        /// </summary>
        public static string Index4_4 {
            get {
                return ResourceManager.GetString("Index4.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architecture.
        /// </summary>
        public static string Index5_0 {
            get {
                return ResourceManager.GetString("Index5.0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graphical user interface of Flix Manager is divided into three main sections:.
        /// </summary>
        public static string Index6_0 {
            get {
                return ResourceManager.GetString("Index6.0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Horizontal Navigation Bar on Top.
        /// </summary>
        public static string Index7_1 {
            get {
                return ResourceManager.GetString("Index7.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Register&quot;, &quot;Log in&quot;, and &quot;Log out&quot; links are the representation of the.
        /// </summary>
        public static string Index7_10 {
            get {
                return ResourceManager.GetString("Index7.10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to security.
        /// </summary>
        public static string Index7_11 {
            get {
                return ResourceManager.GetString("Index7.11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to module that controls access to different application resources based on the authorization credentials used to.
        /// </summary>
        public static string Index7_12 {
            get {
                return ResourceManager.GetString("Index7.12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register.
        /// </summary>
        public static string Index7_13 {
            get {
                return ResourceManager.GetString("Index7.13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string Index7_14 {
            get {
                return ResourceManager.GetString("Index7.14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or logout an application user..
        /// </summary>
        public static string Index7_15 {
            get {
                return ResourceManager.GetString("Index7.15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registration process includes.
        /// </summary>
        public static string Index7_16 {
            get {
                return ResourceManager.GetString("Index7.16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account confirmation.
        /// </summary>
        public static string Index7_17 {
            get {
                return ResourceManager.GetString("Index7.17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and has options such as:.
        /// </summary>
        public static string Index7_18 {
            get {
                return ResourceManager.GetString("Index7.18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling .
        /// </summary>
        public static string Index7_19 {
            get {
                return ResourceManager.GetString("Index7.19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top level navigation bar found at the very top of the graphical user interface..
        /// </summary>
        public static string Index7_2 {
            get {
                return ResourceManager.GetString("Index7.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two factor authentication.
        /// </summary>
        public static string Index7_20 {
            get {
                return ResourceManager.GetString("Index7.20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to increase security..
        /// </summary>
        public static string Index7_21 {
            get {
                return ResourceManager.GetString("Index7.21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application user authentication with.
        /// </summary>
        public static string Index7_22 {
            get {
                return ResourceManager.GetString("Index7.22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to external ID providers.
        /// </summary>
        public static string Index7_23 {
            get {
                return ResourceManager.GetString("Index7.23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to such as Google and Facebook..
        /// </summary>
        public static string Index7_24 {
            get {
                return ResourceManager.GetString("Index7.24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is the doorway to an application user&apos;s.
        /// </summary>
        public static string Index7_25 {
            get {
                return ResourceManager.GetString("Index7.25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to personal profile.
        /// </summary>
        public static string Index7_26 {
            get {
                return ResourceManager.GetString("Index7.26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to access, download, update, or delete your account information at any time..
        /// </summary>
        public static string Index7_27 {
            get {
                return ResourceManager.GetString("Index7.27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order of appearance:.
        /// </summary>
        public static string Index7_3 {
            get {
                return ResourceManager.GetString("Index7.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bell icon allows the user to subscribe to the.
        /// </summary>
        public static string Index7_4 {
            get {
                return ResourceManager.GetString("Index7.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to web push notification service.
        /// </summary>
        public static string Index7_5 {
            get {
                return ResourceManager.GetString("Index7.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The drop down menu is the implementation of.
        /// </summary>
        public static string Index7_6 {
            get {
                return ResourceManager.GetString("Index7.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internationalization.
        /// </summary>
        public static string Index7_7 {
            get {
                return ResourceManager.GetString("Index7.7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to which retrieves your web browser&apos;s language preferences to display the web page content in the same language when available..
        /// </summary>
        public static string Index7_8 {
            get {
                return ResourceManager.GetString("Index7.8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The drop down control allows the user to override the web browser&apos;s preferences and select the language of choice. This is just for demonstration purposes and it is not available everywhere in the application..
        /// </summary>
        public static string Index7_9 {
            get {
                return ResourceManager.GetString("Index7.9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Flix Manager Menu.
        /// </summary>
        public static string Index8_1 {
            get {
                return ResourceManager.GetString("Index8.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Index8_10 {
            get {
                return ResourceManager.GetString("Index8.10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to movies, actors, and genres..
        /// </summary>
        public static string Index8_11 {
            get {
                return ResourceManager.GetString("Index8.11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filters.
        /// </summary>
        public static string Index8_12 {
            get {
                return ResourceManager.GetString("Index8.12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and .
        /// </summary>
        public static string Index8_13 {
            get {
                return ResourceManager.GetString("Index8.13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test authorized operations based on the .
        /// </summary>
        public static string Index8_14 {
            get {
                return ResourceManager.GetString("Index8.14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authorization claims.
        /// </summary>
        public static string Index8_15 {
            get {
                return ResourceManager.GetString("Index8.15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of built-in.
        /// </summary>
        public static string Index8_16 {
            get {
                return ResourceManager.GetString("Index8.16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application users.
        /// </summary>
        public static string Index8_17 {
            get {
                return ResourceManager.GetString("Index8.17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string Index8_18 {
            get {
                return ResourceManager.GetString("Index8.18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has access to most of the available sections but is not allowed to perform create, update, or delete operations..
        /// </summary>
        public static string Index8_19 {
            get {
                return ResourceManager.GetString("Index8.19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top level navigation menu item found right at the top of the vertical navigation bar on the left column of the graphical user interface..
        /// </summary>
        public static string Index8_2 {
            get {
                return ResourceManager.GetString("Index8.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest user login info.
        /// </summary>
        public static string Index8_20 {
            get {
                return ResourceManager.GetString("Index8.20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Index8_21 {
            get {
                return ResourceManager.GetString("Index8.21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Index8_22 {
            get {
                return ResourceManager.GetString("Index8.22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        public static string Index8_23 {
            get {
                return ResourceManager.GetString("Index8.23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has access to most of the available sections and is allowed to perform create but not edit or delete operations..
        /// </summary>
        public static string Index8_24 {
            get {
                return ResourceManager.GetString("Index8.24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator user login info.
        /// </summary>
        public static string Index8_25 {
            get {
                return ResourceManager.GetString("Index8.25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Index8_26 {
            get {
                return ResourceManager.GetString("Index8.26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has administrator privileges to access all the features available including editing other user&apos;s permissions..
        /// </summary>
        public static string Index8_27 {
            get {
                return ResourceManager.GetString("Index8.27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login info for.
        /// </summary>
        public static string Index8_28 {
            get {
                return ResourceManager.GetString("Index8.28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides access to the operational module. This is where you can make use of most of the application features..
        /// </summary>
        public static string Index8_3 {
            get {
                return ResourceManager.GetString("Index8.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some examples of the available operations are:.
        /// </summary>
        public static string Index8_4 {
            get {
                return ResourceManager.GetString("Index8.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search using.
        /// </summary>
        public static string Index8_5 {
            get {
                return ResourceManager.GetString("Index8.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pagination.
        /// </summary>
        public static string Index8_6 {
            get {
                return ResourceManager.GetString("Index8.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string Index8_7 {
            get {
                return ResourceManager.GetString("Index8.7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update.
        /// </summary>
        public static string Index8_8 {
            get {
                return ResourceManager.GetString("Index8.8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and/or.
        /// </summary>
        public static string Index8_9 {
            get {
                return ResourceManager.GetString("Index8.9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Nav Menu Items 01 to 13.
        /// </summary>
        public static string Index9_1 {
            get {
                return ResourceManager.GetString("Index9.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to installed.
        /// </summary>
        public static string Index9_10 {
            get {
                return ResourceManager.GetString("Index9.10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to into the start menu, dock, or home screen depending on the web browser used and the operating system in which it used (e.g., Windows, macOS, iOS, or Android)..
        /// </summary>
        public static string Index9_11 {
            get {
                return ResourceManager.GetString("Index9.11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typically, you will see an icon next to the web browser&apos;s address bar to install the application..
        /// </summary>
        public static string Index9_12 {
            get {
                return ResourceManager.GetString("Index9.12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It progressively establishes offline support attending the most frequently visited areas by the user..
        /// </summary>
        public static string Index9_13 {
            get {
                return ResourceManager.GetString("Index9.13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feel free to play around and experiment every scenario you can imagine without hesitation. There is a.
        /// </summary>
        public static string Index9_14 {
            get {
                return ResourceManager.GetString("Index9.14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button element in the.
        /// </summary>
        public static string Index9_15 {
            get {
                return ResourceManager.GetString("Index9.15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to routable component that completely wipes out all the data and resets the database into its initial state..
        /// </summary>
        public static string Index9_16 {
            get {
                return ResourceManager.GetString("Index9.16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The.
        /// </summary>
        public static string Index9_17 {
            get {
                return ResourceManager.GetString("Index9.17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to progressive web application was not created with a focus on the design of the graphical user interface to keep things as simple as the requirements permit. The focus was primarily on the architecture of the source code and the way the components interact with each other (structure)..
        /// </summary>
        public static string Index9_18 {
            get {
                return ResourceManager.GetString("Index9.18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top level navigation menu items found right below Flix Manager in the vertical navigation bar on the left column of the graphical user interface..
        /// </summary>
        public static string Index9_2 {
            get {
                return ResourceManager.GetString("Index9.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nav menu items provide access to the instructional module of the application. This is where we demonstrate how to implement each of the features available in the operational sections of the graphical user interface cited earlier..
        /// </summary>
        public static string Index9_3 {
            get {
                return ResourceManager.GetString("Index9.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each top level navigation menu has an introduction to the topic and includes submenus that slowly progress from the fundamental concepts to the more advanced implementations..
        /// </summary>
        public static string Index9_4 {
            get {
                return ResourceManager.GetString("Index9.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Notes.
        /// </summary>
        public static string Index9_5 {
            get {
                return ResourceManager.GetString("Index9.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a.
        /// </summary>
        public static string Index9_6 {
            get {
                return ResourceManager.GetString("Index9.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to progressive web application.
        /// </summary>
        public static string Index9_7 {
            get {
                return ResourceManager.GetString("Index9.7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and as such, it can behave like a desktop (or native) application. For example,.
        /// </summary>
        public static string Index9_8 {
            get {
                return ResourceManager.GetString("Index9.8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It can be.
        /// </summary>
        public static string Index9_9 {
            get {
                return ResourceManager.GetString("Index9.9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flix Manager Progressive Web App.
        /// </summary>
        public static string MainHeader {
            get {
                return ResourceManager.GetString("MainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flix Manager Intro.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preface.
        /// </summary>
        public static string Preface {
            get {
                return ResourceManager.GetString("Preface", resourceCulture);
            }
        }
    }
}
